[metadata]
name = pysatview
author = Group 12 
author_email = william.edge@uwa.edu.au
description = Python package for satellite data downloading.
license = BSD-3-Clause
long_description_content_type = text/markdown
url = https://github.com/TIDE-ITRH/pysatview
project_urls =
    Bug Tracker = https://github.com/TIDE-ITRH/pysatview/issues
    Changelog = https://github.com/TIDE-ITRH/pysatview/releases
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: BSD License
    Intended Audience :: Developers

[options]
package_dir =
    = src
packages = find:
install_requires =
    numpy
	pandas
    xarray
    matplotlib
    cmocean
	earthaccess
	owslib
    eumdac
	tqdm
    IProgress
	notebook
	ipykernel
	urllib3
    seaborn
    netcdf4
    python-dateutil
    pathlib2
    cartopy

[options.packages.find]
where = src

[options.entry_points]
console_scripts =
    pysatview = pysatview.app:entry_point